# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='directory',
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='file',
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='repository',
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='directory',
            name='last_commit',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_commit',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='repository',
            name='last_commit',
            field=models.CharField(max_length=150),
        ),
    ]
