# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_file_last_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_dirs', to='health.Directory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_files', to='health.Directory'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='health.Directory'),
        ),
    ]
